In [81]:
import pandas as pd
import numpy as np
import torch
from matplotlib import pyplot as plt

In [82]:
"""Initiate Data"""
data = pd.read_csv("MNIST_CSV/mnist_train.csv")

In [83]:
"""Format Data Sets - Development set and Training set"""

data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev= data[0:1000].T 
Y_dev = data_dev[0]
X_dev = data_dev[1:n]

data_train = data[1000:m].T 
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.0
X_dev = X_dev / 255.0


In [84]:
"""Initiate Parameters"""
def init_params():
    W1 = np.random.randn(64, 784) * 0.01
    b1 = np.zeros((64, 1 ))
    W2 = np.random.randn(10, 64) * 0.01
    b2 = np.zeros((10, 1))
    return W1, b1, W2, b2

"""Can also use sigmoid function, ReLU more common for hidden layers, softmax for output layer"""
def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    expZ = np.exp(Z - np.max(Z, axis=0, keepdims=True))
    return expZ / np.sum(expZ, axis=0, keepdims=True)

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2
    
"""Creates output layer with 10 neurons"""
def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T 
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W2, X, Y): 
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2, axis=1, keepdims=True)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1, axis=1, keepdims=True)
    return dW1, db1, dW2, db2

def update_params(dW1, db1, dW2, db2, W1, b1,  W2, b2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [85]:
def get_predictions(A2):
    return np.argmax(A2,0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W2, X, Y)
        W1, b1, W2, b2 = update_params(dW1, db1, dW2, db2, W1, b1, W2,b2, alpha)
        if i % 10 == 0:
            print("Iteration: ", i)
            print("Accuracy: ", get_accuracy(get_predictions(A2), Y))
    return W1, b1, W2, b2

In [86]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.05)

Iteration:  0
[6 4 9 ... 0 9 0] [9 2 4 ... 0 7 7]
Accuracy:  0.08773030051356803
Iteration:  10
[3 0 9 ... 0 9 3] [9 2 4 ... 0 7 7]
Accuracy:  0.22991915117205378
Iteration:  20
[3 0 9 ... 0 2 1] [9 2 4 ... 0 7 7]
Accuracy:  0.31358158612857845
Iteration:  30
[3 0 9 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.34881947151646636
Iteration:  40
[2 0 9 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.36202308513703624
Iteration:  50
[0 0 9 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.36148070306276375
Iteration:  60
[0 0 4 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.3572772419871523
Iteration:  70
[0 0 4 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.35937897252495804
Iteration:  80
[7 0 4 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.3716334175155511
Iteration:  90
[7 0 4 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.39824403803454295
Iteration:  100
[7 0 4 ... 0 2 7] [9 2 4 ... 0 7 7]
Accuracy:  0.4423464804488212
Iteration:  110
[7 0 7 ... 0 9 7] [9 2 4 ... 0 7 7]
Accuracy:  0.4998220308818794
Iteration:  120
[7 